
### show list of posts
GET http://localhost:3000/


### post comment
POST http://localhost:3000/user/comments
Content-Type: application/json

{
	"email": "valie@hotmail.com",
	"name": "jhon",
	"comment": "some comment",
	"post": "663e3930447e983e8d6dcf7d"
}


###

POST http://localhost:3000/user/sign-up
Content-Type: application/json

{
    "first_name": "jhon",
	"last_name": "dow",
	"username": "jhondow",
	"password": "admin123",
    "passwordConfirmation": "admin123"
}

###

POST http://localhost:3000/user/log-in
Content-Type: application/json

{
	"username": "josueuser",
	"password": "user1234"
}

###

POST http://localhost:3000/user/create-post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNiODg1YmQ1NDg1MTEyOGRkNzI2OTYiLCJmaXJzdF9uYW1lIjoiam9zdWUiLCJsYXN0X25hbWUiOiJkZSBsb3Mgc2FudG9zIiwidXNlcm5hbWUiOiJqb3N1ZXNpdG8iLCJwYXNzd29yZCI6IiQyYSQxMCRlc09iRGRNNEttMWxqVWlkOE9ldGl1ZnhHSVNmZVZPTmp4bVB3MzNvVmJ1cVdIOVZxb2tCMiIsIl9fdiI6MCwiaWF0IjoxNzE1MTkyNTc1LCJleHAiOjE3MTUyNzg5NzV9.TirZdvHDp1IqgLsSoe2SMITE2hHIWq7dFYgXE30x2NA

{
	"title": "3 example title",
	"description": "This is the description",
	"post": "2 example post",
	"author": "Jhon Dow",
	"file": ""
}

###

PATCH http://localhost:3000/user/posts/663fd7e95d892b78a1c58520
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNlMzI0YTA5OGQ1ZjU4ZjAwODU1MzkiLCJmaXJzdF9uYW1lIjoiam9zdWUiLCJsYXN0X25hbWUiOiJkZSBsb3Mgc2FudG9zIiwidXNlcm5hbWUiOiJqb3N1ZXNpdG8iLCJwYXNzd29yZCI6IiQyYSQxMCRmdExkVXNOWWxhSmt5aGpLejlvMEl1eVBIT0lMQlBVY3dsS2Z4cmdTRUZQbi5zNTlab0NJYSIsIl9fdiI6MCwiaWF0IjoxNzE1NDYwMDYzLCJleHAiOjE3MTU0NjM2NjN9.nKSCfpZd5vZLEOMY5LAXOLSzE-XNO301tST7BqLx6Qk

{
	"title": "4 example title",
	"description": "This is the description",
	"post": "2 example post",
	"author": "Jhon Dow",
	"comments": ["663fd7f85d892b78a1c58528", "663fd7f15d892b78a1c58524"],
	"file": ""
}
###

DELETE http://localhost:3000/user/posts/663fee860907d3bf2adc8227
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWRiYWFiMjg3NGNkNWY5ZTdmZGUyMTEiLCJmaXJzdF9uYW1lIjoiSm9zdWUiLCJsYXN0X25hbWUiOiJEZSBsb3Mgc2FudG9zIiwidXNlcm5hbWUiOiJqb3N1ZXNpdG8iLCJwYXNzd29yZCI6IiQyYSQxMCR5QU1xci9kUXNxQVRYU1hxNXF5dUFPZWFTaVpBeEgwNHd2dE8zdzBJbnVNY0tnNnJZQVlLUyIsIl9fdiI6MCwiaWF0IjoxNzA4ODk0OTAyLCJleHAiOjE3MDg5ODEzMDJ9.tiVjtTkWGRvVZnrx1K88U02QKcK8XSQFwLLmEqVC4b0

###

POST http://localhost:3000/user/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQwZGEwNDdlNTA5YzE2ZGU0NTI2NTgiLCJmaXJzdF9uYW1lIjoiam9zdWUiLCJsYXN0X25hbWUiOiJkZSBsb3Mgc2FudG9zIiwidXNlcm5hbWUiOiJqb3N1ZXNpdG8iLCJwYXNzd29yZCI6IiQyYSQxMCRCUEx2ZC45RWM5U0gxWi9XWXpqVUV1RWlRS0N1Z3k2R3FYVWtURm9vU1d3eXdzcTNFZk1zLiIsIl9fdiI6MCwiaWF0IjoxNzE1NTI2MTczLCJleHAiOjE3MTU2MTI1NzN9.Zag3jkyfcgESfKFFKUJPsoYHQRhFrnrcL7QWhujQRgg

{
	"email": "josh@email.com",
	"name": "josh",
	"comment": "message 16",
	"post": "6640dc6ab1ed525addc11b90"
}

###

GET http://localhost:3000/user/posts/663fca1acafb2e7346d4cc19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNlMzI0YTA5OGQ1ZjU4ZjAwODU1MzkiLCJmaXJzdF9uYW1lIjoiam9zdWUiLCJsYXN0X25hbWUiOiJkZSBsb3Mgc2FudG9zIiwidXNlcm5hbWUiOiJqb3N1ZXNpdG8iLCJwYXNzd29yZCI6IiQyYSQxMCRmdExkVXNOWWxhSmt5aGpLejlvMEl1eVBIT0lMQlBVY3dsS2Z4cmdTRUZQbi5zNTlab0NJYSIsIl9fdiI6MCwiaWF0IjoxNzE1NDU2Mjc1LCJleHAiOjE3MTU0NTk4NzV9.Z6aIr0qrhtPV38tC9ns37k98QvnkmU0RzQqrgl5E1gI

###