
### show list of posts
GET http://localhost:3000/


### post comment
POST http://localhost:3000/comments
Content-Type: application/json

{
	"email": "valie@hotmail.com",
	"name": "jhon",
	"comment": "some comment",
	"post": "662ec690919e990a187616a1"
}


###

POST http://localhost:3000/user/sign-up
Content-Type: application/json

{
    "first_name": "jhon",
	"last_name": "dow",
	"username": "jhondow",
	"password": "admin123",
    "passwordConfirmation": "admin123"
}

###

POST http://localhost:3000/user/log-in
Content-Type: application/json

{
	"username": "josuesito0",
	"password": "admin123"
}

###

POST http://localhost:3000/user/create-post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNiODg1YmQ1NDg1MTEyOGRkNzI2OTYiLCJmaXJzdF9uYW1lIjoiam9zdWUiLCJsYXN0X25hbWUiOiJkZSBsb3Mgc2FudG9zIiwidXNlcm5hbWUiOiJqb3N1ZXNpdG8iLCJwYXNzd29yZCI6IiQyYSQxMCRlc09iRGRNNEttMWxqVWlkOE9ldGl1ZnhHSVNmZVZPTmp4bVB3MzNvVmJ1cVdIOVZxb2tCMiIsIl9fdiI6MCwiaWF0IjoxNzE1MTkyNTc1LCJleHAiOjE3MTUyNzg5NzV9.TirZdvHDp1IqgLsSoe2SMITE2hHIWq7dFYgXE30x2NA

{
	"title": "3 example title",
	"description": "This is the description",
	"post": "2 example post",
	"author": "Jhon Dow",
	"file": ""
}

###

GET http://localhost:3000/user/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWZjNjEzNTE1ZjRkN2U1ZDk2YWI4ZTUiLCJmaXJzdF9uYW1lIjoiamhvbiIsImxhc3RfbmFtZSI6ImRvdyIsInVzZXJuYW1lIjoiamhvbmRvdyIsInBhc3N3b3JkIjoiJDJhJDEwJFYxWEd3Z1FCSVBWck1QSlEyaVpJL2V2b3dXbUtQbC8wNEpnc2pCLlNOb0dHODNYbnMuUWJ1IiwiX192IjowLCJpYXQiOjE3MTEwMzg3NzgsImV4cCI6MTcxMTEyNTE3OH0.R9DrxM1CRzybvckReo_rl2v_qDhMw2NIVHHXBO08TRs

###

DELETE http://localhost:3000/user/posts/65fc617c15f4d7e5d96ab8ea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWRiYWFiMjg3NGNkNWY5ZTdmZGUyMTEiLCJmaXJzdF9uYW1lIjoiSm9zdWUiLCJsYXN0X25hbWUiOiJEZSBsb3Mgc2FudG9zIiwidXNlcm5hbWUiOiJqb3N1ZXNpdG8iLCJwYXNzd29yZCI6IiQyYSQxMCR5QU1xci9kUXNxQVRYU1hxNXF5dUFPZWFTaVpBeEgwNHd2dE8zdzBJbnVNY0tnNnJZQVlLUyIsIl9fdiI6MCwiaWF0IjoxNzA5Njg2MDkwLCJleHAiOjE3MDk3NzI0OTB9.TtZBN9J3mGpWS9i1G-lpa795vBoKn2CYv-YE9NacDZ8

###

DELETE http://localhost:3000/user/comments/65dbab39874cd5f9e7fde21a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWRiYWFiMjg3NGNkNWY5ZTdmZGUyMTEiLCJmaXJzdF9uYW1lIjoiSm9zdWUiLCJsYXN0X25hbWUiOiJEZSBsb3Mgc2FudG9zIiwidXNlcm5hbWUiOiJqb3N1ZXNpdG8iLCJwYXNzd29yZCI6IiQyYSQxMCR5QU1xci9kUXNxQVRYU1hxNXF5dUFPZWFTaVpBeEgwNHd2dE8zdzBJbnVNY0tnNnJZQVlLUyIsIl9fdiI6MCwiaWF0IjoxNzA4ODk0OTAyLCJleHAiOjE3MDg5ODEzMDJ9.tiVjtTkWGRvVZnrx1K88U02QKcK8XSQFwLLmEqVC4b0

###

POST http://localhost:3000
Content-Type: application/json

{
	"email": "josh@email.com",
	"comment": "sample comment 3",
	"post": "65fcbabd90b9e936f90b8f85"
}

###

GET http://localhost:3000/user/posts/663a98e81e82954be0a65f70
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNhOThkOTFlODI5NTRiZTBhNjVmNmIiLCJmaXJzdF9uYW1lIjoiam9zdWUiLCJsYXN0X25hbWUiOiJkZSBsb3Mgc2FudG9zIiwidXNlcm5hbWUiOiJqb3N1ZXNpdG8iLCJwYXNzd29yZCI6IiQyYSQxMCRmcEw2V0JneTI5U2ZlaTQvM1lyaVR1bGVTajgzamhHRmNOdHRSNWZMRkFqRWFqNW40SC8uLiIsIl9fdiI6MCwiaWF0IjoxNzE1MTE2NTMwLCJleHAiOjE3MTUyMDI5MzB9.hm_B9fH2vgSErCylFTcZ-x_XDDyFlRKEJserzay7uLQ

###